env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_db2:
    name: DB2 ${{ matrix.db2 }}
    runs-on: self-hosted
    services:
      db2:
        env:
          ARCHIVE_LOGS: false
          AUTOCONFIG: false
          DB2INST1_PASSWORD: flowable
          DBNAME: flowable
          LICENSE: accept
        image: ibmcom/db2:${{ matrix.db2 }}
        options: --privileged=true --health-cmd="su - db2inst1 -c \"~/sqllib/bin/db2
          connect to flowable && ~/sqllib/bin/db2 connect reset\"" --health-interval
          30s --health-timeout 40s --health-retries 10
        ports:
        - 50000:50000
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,db2 -Djdbc.url=jdbc:db2://localhost:${{
        job.services.db2.ports[50000] }}/flowable -Djdbc.username=db2inst1 -Djdbc.password=flowable
        -Djdbc.driver=com.ibm.db2.jcc.DB2Driver -Dmaven.test.redirectTestOutputToFile=false
    strategy:
      fail-fast: false
      matrix:
        db2:
        - 11.5.0.0a
  test_db2_dmn:
    name: DB2 ${{ matrix.db2 }} DMN
    runs-on: self-hosted
    services:
      db2:
        env:
          ARCHIVE_LOGS: false
          AUTOCONFIG: false
          DB2INST1_PASSWORD: flowable
          DBNAME: flowable
          LICENSE: accept
        image: ibmcom/db2:${{ matrix.db2 }}
        options: --privileged=true --health-cmd="su - db2inst1 -c \"~/sqllib/bin/db2
          connect to flowable && ~/sqllib/bin/db2 connect reset\"" --health-interval
          30s --health-timeout 40s --health-retries 10
        ports:
        - 50000:50000
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -Pdmn,db2 -Djdbc.url=jdbc:db2://localhost:${{
        job.services.db2.ports[50000] }}/flowable -Djdbc.username=db2inst1 -Djdbc.password=flowable
        -Djdbc.driver=com.ibm.db2.jcc.DB2Driver -Dmaven.test.redirectTestOutputToFile=false
        -pl org.flowable:flowable-dmn-engine -am
    strategy:
      fail-fast: false
      matrix:
        db2:
        - 11.5.0.0a
name: Flowable DB2 Build
on:
  repository_dispatch:
    types: trigger-ga___db2.yml
