jobs:
  release_docker_images_with_latest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      id: meta
      name: Get current project meta
      run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version
        -q -DforceStdout)"
    - continue-on-error: true
      name: Build Docker images with Maven
      run: 'mvn clean package -B -Dstyle.color=always \

        -P dockerDeps,dockerPublishWithLatest \

        -pl :flowable-app-rest \

        -Ddocker.publisher.user=${{ secrets.DOCKER_USER }} \

        -Ddocker.publisher.password=${{ secrets.DOCKER_PASSWORD }}

        '
    - continue-on-error: true
      name: Install cosign
      uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
      with:
        cosign-release: v1.7.1
    - continue-on-error: true
      name: Write signing key to disk
      run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key
    - continue-on-error: true
      name: Log into dockerhub
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USER }}
    - continue-on-error: true
      env:
        COSIGN_PASSWORD: ''
      name: Sign the published Docker images
      run: "cosign sign --key cosign.key \\\n  -a \"repo=${{ github.repository }}\"\
        \ \\\n  -a \"ref=${{ github.sha }}\" \\\n  flowable/flowable-rest:${{ steps.meta.outputs.version\
        \ }} \ncosign sign --key cosign.key \\\n  -a \"repo=${{ github.repository\
        \ }}\" \\\n  -a \"ref=${{ github.sha }}\" \\\n  flowable/flowable-rest:latest"
name: Release Docker Images With Latest
on:
  repository_dispatch:
    types: trigger-ga___docker-release-with-latest.yml
