jobs:
  test_jdk:
    env:
      MAVEN_CONFIG: -V -B --no-transfer-progress
    name: Flowable 5 Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Build and Test
      run: cd scripts && ./run-flowable5-tests.sh
name: Flowable 5 Build
on:
  repository_dispatch:
    types: trigger-ga___flowable5.yml
