env:
  MAVEN_ARGS: -B -V --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_graal:
    name: Linux Graal Native
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: graalvm
        java-version: 17
    - continue-on-error: true
      name: Cache Maven Repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Install
      run: ./mvnw install -Pdistro ${MAVEN_ARGS} -DskipTests=true -Dmaven.javadoc.skip=true
    - continue-on-error: true
      name: Test
      run: ./mvnw test -PnativeTest,native,distro,errorLogging ${MAVEN_ARGS} -Dmaven.test.redirectTestOutputToFile=false
        -pl modules/flowable-spring-boot/flowable-spring-boot-samples/flowable-spring-boot-sample-native
name: Flowable Graal Build
on:
  repository_dispatch:
    types: trigger-ga___graal-native.yml
