jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Configure Git
      run: 'git config user.name "$GITHUB_ACTOR"

        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        '
    - continue-on-error: true
      name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - continue-on-error: true
      env:
        CR_GIT_REPO: flowable.github.io
        CR_OWNER: flowable
        CR_PACKAGE_PATH: helm
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.1
      with:
        charts_dir: k8s/flowable
        charts_repo_url: https://flowable.github.io/helm/
name: Release Helm Charts
on:
  repository_dispatch:
    types: trigger-ga___helm-release.yml
