env:
  MAVEN_ARGS: -B -V --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_jdkea:
    name: Linux (OpenJDK EA)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Maven Repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        release: EA
        website: jdk.java.net
    - continue-on-error: true
      name: Install
      run: ./mvnw install ${MAVEN_ARGS} -DskipTests=true -Dmaven.javadoc.skip=true
        -B -V
    - continue-on-error: true
      name: Test
      run: ./mvnw verify -Pdistro,errorLogging ${MAVEN_ARGS} -Dmaven.test.redirectTestOutputToFile=false
name: Flowable Java EA Build
on:
  repository_dispatch:
    types: trigger-ga___java-ea.yml
