env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_mariadb:
    name: MariaDB ${{ matrix.mariadb }}
    runs-on: self-hosted
    services:
      mariadb:
        env:
          MARIADB_DATABASE: flowable
          MARIADB_PASSWORD: flowable
          MARIADB_ROOT_PASSWORD: flowable
          MARIADB_USER: flowable
        image: mariadb:${{ matrix.mariadb }}
        options: --health-cmd="mariadb-admin -uflowable -pflowable status" --health-interval
          10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mariadb:rw
        ports:
        - 3306/tcp
    steps:
    - continue-on-error: true
      name: Set MariaDB collation
      run: docker exec ${{ job.services.mariadb.id }} sh -c 'mysql --user=flowable
        --password=flowable --database=flowable --execute="alter database flowable
        character set utf8mb4 collate utf8mb4_bin"'
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,mariadb -Djdbc.url=jdbc:mariadb://localhost:${{
        job.services.mariadb.ports[3306] }}/flowable?characterEncoding=UTF-8 -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=org.mariadb.jdbc.Driver -Dmaven.test.redirectTestOutputToFile=false
    strategy:
      fail-fast: false
      matrix:
        mariadb:
        - 10.6
  test_mariadb_dmn:
    name: MariadDB ${{ matrix.mariadb }} DMN
    runs-on: self-hosted
    services:
      mariadb:
        env:
          MARIADB_DATABASE: flowable
          MARIADB_PASSWORD: flowable
          MARIADB_ROOT_PASSWORD: flowable
          MARIADB_USER: flowable
        image: mariadb:${{ matrix.mariadb }}
        options: --health-cmd="mariadb-admin -uflowable -pflowable status" --health-interval
          10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mariadb:rw
        ports:
        - 3306/tcp
    steps:
    - continue-on-error: true
      name: Set MariaDB collation
      run: docker exec ${{ job.services.mariadb.id }} sh -c 'mysql --user=flowable
        --password=flowable --database=flowable --execute="alter database flowable
        character set utf8mb4 collate utf8mb4_bin"'
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -Pdmn,mariadb -Djdbc.url=jdbc:mariadb://localhost:${{
        job.services.mariadb.ports[3306] }}/flowable?characterEncoding=UTF-8 -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=org.mariadb.jdbc.Driver -Dmaven.test.redirectTestOutputToFile=false
        -pl org.flowable:flowable-dmn-engine -am
    strategy:
      fail-fast: false
      matrix:
        mariadb:
        - 10.6
name: Flowable MariaDB Build
on:
  repository_dispatch:
    types: trigger-ga___mariadb.yml
