env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_mysql:
    name: MySQL ${{ matrix.mysql }}
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_DATABASE: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
          MYSQL_USER: flowable
        image: mysql:${{ matrix.mysql }}
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval
          10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
        ports:
        - 3306/tcp
    steps:
    - continue-on-error: true
      name: Set MySQL collation
      run: docker exec ${{ job.services.mysql.id }} sh -c 'mysql --user=flowable --password=flowable
        --database=flowable --execute="alter database flowable character set utf8mb4
        collate utf8mb4_bin"'
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,mysql -Djdbc.url=jdbc:mysql://localhost:${{
        job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8 -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=com.mysql.cj.jdbc.Driver -Dmaven.test.redirectTestOutputToFile=false
    strategy:
      fail-fast: false
      matrix:
        mysql:
        - 5.7
        - 8.0
  test_mysql_dmn:
    name: MySQL ${{ matrix.mysql }} DMN
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_DATABASE: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
          MYSQL_USER: flowable
        image: mysql:${{ matrix.mysql }}
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval
          10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
        ports:
        - 3306/tcp
    steps:
    - continue-on-error: true
      name: Set MySQL collation
      run: docker exec ${{ job.services.mysql.id }} sh -c 'mysql --user=flowable --password=flowable
        --database=flowable --execute="alter database flowable character set utf8mb4
        collate utf8mb4_bin"'
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -Pdmn,mysql -Djdbc.url=jdbc:mysql://localhost:${{
        job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8 -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=com.mysql.cj.jdbc.Driver -Dmaven.test.redirectTestOutputToFile=false
        -pl org.flowable:flowable-dmn-engine -am
    strategy:
      fail-fast: false
      matrix:
        mysql:
        - 5.7
        - 8.0
name: Flowable MySQL Build
on:
  repository_dispatch:
    types: trigger-ga___mysql.yml
