env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_oracle:
    name: Oracle ${{ matrix.oracle }}
    runs-on: self-hosted
    services:
      oracle:
        env:
          APP_USER: flowable
          APP_USER_PASSWORD: flowable
          ORACLE_PASSWORD: flowable
        image: gvenzl/oracle-xe:${{ matrix.oracle }}
        options: --shm-size=2g --health-cmd healthcheck.sh --health-interval 20s --health-timeout
          10s --health-retries 10
        ports:
        - 1521/tcp
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,oracle -Djdbc.url=jdbc:oracle:thin:@localhost:${{
        job.services.oracle.ports[1521] }}/${{ matrix.serviceName }} -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=oracle.jdbc.driver.OracleDriver -Doracle.jdbc.version=${{
        matrix.driverVersion }} -Doracle.jdbc.artifact=${{ matrix.driverArtifact }}
        -Dmaven.test.redirectTestOutputToFile=false
    strategy:
      fail-fast: false
      matrix:
        include:
        - driverArtifact: ojdbc8
          driverVersion: 18.3.0.0
          oracle: 18-slim
          serviceName: XEPDB1
        - driverArtifact: ojdbc8
          driverVersion: 21.6.0.0.1
          oracle: 21-slim
          serviceName: XEPDB1
        oracle:
        - 18-slim
        - 21-slim
  test_oracle_dmn:
    name: Oracle ${{ matrix.oracle }} DMN
    runs-on: self-hosted
    services:
      oracle:
        env:
          APP_USER: flowable
          APP_USER_PASSWORD: flowable
          ORACLE_PASSWORD: flowable
        image: gvenzl/oracle-xe:${{ matrix.oracle }}
        options: --shm-size=2g --health-cmd healthcheck.sh --health-interval 20s --health-timeout
          10s --health-retries 10
        ports:
        - 1521/tcp
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -Pdmn,oracle -Djdbc.url=jdbc:oracle:thin:@localhost:${{
        job.services.oracle.ports[1521] }}/${{ matrix.serviceName }} -Djdbc.username=flowable
        -Djdbc.password=flowable -Djdbc.driver=oracle.jdbc.driver.OracleDriver -Doracle.jdbc.version=${{
        matrix.driverVersion }} -Doracle.jdbc.artifact=${{ matrix.driverArtifact }}
        -Dmaven.test.redirectTestOutputToFile=false -pl org.flowable:flowable-dmn-engine
        -am
    strategy:
      fail-fast: false
      matrix:
        include:
        - driverArtifact: ojdbc8
          driverVersion: 18.3.0.0
          oracle: 18-slim
          serviceName: XEPDB1
        - driverArtifact: ojdbc8
          driverVersion: 21.6.0.0.1
          oracle: 21-slim
          serviceName: XEPDB1
        oracle:
        - 18-slim
        - 21-slim
name: Flowable Oracle Build
on:
  repository_dispatch:
    types: trigger-ga___oracle.yml
