env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_postgres:
    name: Postgres ${{ matrix.postgres }}
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: flowable
          POSTGRES_USER: flowable
        image: postgres:${{ matrix.postgres }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5 --tmpfs /var/lib/postgresql/data:rw
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,postgresql -Djdbc.url=jdbc:postgresql://localhost:${{
        job.services.postgres.ports[5432] }}/flowable -Djdbc.username=flowable -Djdbc.password=flowable
        -Djdbc.driver=org.postgresql.Driver -Dmaven.test.redirectTestOutputToFile=false
    strategy:
      fail-fast: false
      matrix:
        postgres:
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
  test_postgres_dmn:
    name: Postgres ${{ matrix.postgres }} DMN
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: flowable
          POSTGRES_USER: flowable
        image: postgres:${{ matrix.postgres }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5 --tmpfs /var/lib/postgresql/data:rw
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -Pdmn,postgresql -Djdbc.url=jdbc:postgresql://localhost:${{
        job.services.postgres.ports[5432] }}/flowable -Djdbc.username=flowable -Djdbc.password=flowable
        -Djdbc.driver=org.postgresql.Driver -Dmaven.test.redirectTestOutputToFile=false
        -pl org.flowable:flowable-dmn-engine -am
    strategy:
      fail-fast: false
      matrix:
        postgres:
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
name: Flowable Postgres Build
on:
  repository_dispatch:
    types: trigger-ga___postgres.yml
